image : maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - package
  - build
  - push

maven-package:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS package"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: build
  script:
    - "docker build -t beatbox:latest ."

docker-push:
  stage: push
  script:
    - "sudo docker login registry.gitlab.com/vishnu.raj21/no-rhythm-beat-box -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
    - "sudo docker push registry.gitlab.com/vishnu.raj21/no-rhythm-beat-box"
